# R for travis: documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

jobs:
  include:
    - stage: "R CMD check"
      r: oldrel
    - r: release
    - r: devel

    - stage: deploy
      name: covr
      r: release
      r_binary_packages:
        - covr
      script:
        - Rscript -e "covr::codecov()"

    - stage: deploy
      name: pkgdown
      r: release
      if: branch IN (master)
      r_binary_packages:
        - pkgdown
      script:
        - Rscript -e "devtools::install()"
        - Rscript -e "pkgdown::build_site()"
        - Rscript -e "remove.packages(devtools::as.package('.')$package)"
      deploy:
        provider: pages
        local-dir: docs
        skip-cleanup: true
        keep-history: false
        on:
          all_branches: true
        github-token:
          secure: "pgOr8mnAlJeGZOUcyWdiwll7x4sj7A4JCfpHkbIj969hw39+o8ygKCy236B/G1m6sTo/ratc8j7XRhJCDlyqLW/yVJuJLSXOv6muUFZbYlAqueCJGZKVtqv2VPOrzFc9IYlFDXDEs0H6X2FR4rOItPJu9H1m5YBb3gXAVeLf54N40hsr4pMQKEgdutIBaX38MpKCeOBiZBvL+HKL8msunQJYAXPJEa7QoBsBUD2vO5RvjntnjcwUs7jBK2cN2qjIGo5MjEJoXlCoy9uVdMQWxij2oBproTBtSba0jnbVu6dLC1zRMsdmaEvBJ4SoIWSI+MOnSYkwjdnXTR8Lw31j3qeWSbiLImbtb4w7YHwxgUoDCPYcP3fuwZjRsLBv8MiSXwuBAwlna7tlQWPRl3YWjFXIq1H6P62X3PTW4zXysdlWpUs1o57/V6tLCT/kWWHyS7i6VAgaUhM4r03GF9XDS9lvDglK43iV+nrYtvfVAOJ/ZZGdNCmPKs7BHNFOy0L7/GhFE61uNRC3az9THQ00EhnP1v2psq7gjXmbrS6WAaRIJSp6xzZbydGDx9XxNqF1kwmsg5+eP27Fs4fs6QgHDOIYa2wvgIKRysGJz04d8eeUegLxy/hxciJ1Y7BRSl2ApOXoT9siTTd0w0cE7GiNYLttvs4iuModTsdpvGDTdho="
