# R for travis: documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache:
  packages: true
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

notifications:
  email:
    on_success: change
    on_failure: change

jobs:
  include:
    - stage: deploy
      name: covr
      r: release
      cache:
        packages: false
      r_binary_packages:
        - covr
      script:
        - Rscript -e "covr::codecov()"

    - stage: deploy
      name: pkgdown
      r: release
      cache:
        packages: false
      if: |
        branch IN (master, travis) AND \
        type = push AND \
        repo = rstudio/gt
      r_binary_packages:
        - pkgdown
        - remotes
      script:
        - Rscript -e "remotes::install_local()"
        - Rscript -e "pkgdown::build_site()"
        - Rscript -e "remove.packages('gt')"
      deploy:
        provider: pages
        local-dir: docs
        skip-cleanup: true
        keep-history: false
        on:
          all_branches: true
        github-token:
          secure: "GrujWLlpdgy59mI5ZiYnlT8p1LDpqoms/ROeBuFOhJ6tZa6lNYzG4tR2iGkJS5a9hykMbkDootmx95ktC/ovjvFrWXLb8Ql+XiWri1cb17G3SzcEz7m35RA6fKNsu9BVM1qhydBnSS6UtFGWkK/+4dqkT3/3b7XnO2WmF8MtFno9iPnBRybgIYjt5qrBNUZQPcvkjL6FV1x2X2O5lwrH4ND7ueM6wgs5BtxCQxhaBcu9gmDbjlnPsfCbqQvxVNuifguF9AzDPE97nylDyr9jeycehWkvHioFKjYhK/yWfANuXGOgYb0I+vCyxDfxIrOfc+IhUEGaSxqZ3H3fy3Mdc8Bd2+IhC6KbdpSJiB57N1OPIHj6I8a9YlELZN2EczDXUxfvppTlDYBAWUpfI2uPoBMskBTgPXP838u+jNrAcMERkNAIgb4VOPVnf+MbGei2gfSWXmFvH+z0EjwpPxhv0nP1+5TT2RsErwpEyrA8qO14uICx+/gKPZulMKeZApjWYtOyJRjeRYPFUwrLx8S52CeR1el5QyiuPke9oTxmg9gMuoVWGReoDvtOIaz6LbgUPy9/o+gHNPb70DLYii9h2thzJtMTr30jnpGsosIaBghpregaOvxEIyo5xJGRBn9z0R1n6VnRWjyIC/VTh0ljn1pvC26LVrQj7DKa8SMP6Jw="
