# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

jobs:
  include:
  - r: oldrel
  - r: release
  - r: devel
  - os: osx
    r: release

r_binary_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
