# R for travis: documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change

jobs:
  include:
    - stage: "R CMD check"
      r: oldrel
    - r: release
    - r: devel

    - stage: deploy
      name: covr
      r: release
      r_binary_packages:
        - covr
      script:
        - Rscript -e "covr::codecov()"

    - stage: deploy
      name: pkgdown
      r: release
      if: branch IN (master)
      r_binary_packages:
        - pkgdown
      script:
        - Rscript -e "devtools::install()"
        - Rscript -e "pkgdown::build_site()"
        - Rscript -e "remove.packages(devtools::as.package('.')$package)"
      deploy:
        provider: pages
        local-dir: docs
        skip-cleanup: true
        keep-history: false
        on:
          all_branches: true
        github-token:
          secure: "t0ptkdtF5O1xVlQB4rIlh3wYqR7uwkaLWxNih/KLhBIum93nSvBd5gW1lHeW26RFWD6uhXC0S1ei4BsddScBr8oanW2cRTQ7FsMl3Qd3r1ihUu5v0L8ZjuqqR73NfFyzO5zJkvNO5PDV9/TGBopv6qej4riOBPPNCTqDtsAugUY+tyh/4pPlxV/ObB7dMmgtsLQzrxsj0xjRsuh+zGpL0gRrDiPRa5OgsOhVZi+RJgsVyDw/Rm9Qb3qImxMRR5ipJCUpSQcAghaMTI9+y2N/4lp5YAMHkGBNCKMBCNooEcwkAL2Mtz9MW3jWybvl+E6RTn2Ti2QJ8ZDT443JMt5wdCaQZtmxLo9hUEfs5fwv4R6XOm7H4vjogTkeY4BHnsAbMdZKQX+crBByyBJTigH7kkCybTL5CHkuAi1DqVNuO6ZZF7Z/uKXFxvQU9AjSsIZq8fM0QYSATiqpx9XCcWhtza1gjlwsYH5lPIXmmivflBcbQIA98Tf7LiM3skE5Yb+PZI9qoTx6O4CKCClnRNiyIauun4Y47r6s8lR/kZQ8VbcsH6SO+w8ivmcvZ1hmU/MyzCvvE24ywL6CVUvR9eax2Og5xNNphbWB38M4wxGKaZh3vebs1+yMTHHKdhgJTBqSSRGruj1Ng3mt9tso320hgOGZWLiG/2sPIDOmP7cJ1GM="
