codecov:
  token: 3d46ae7b-b709-47c8-a852-bb6e5650e3e7

comment: false

coverage:
  range: "50...95"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
