---
title: "Case Study: Simple Table from the Economist"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Case Study: Simple Table from the Economist}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r options, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>")

library(gt)
library(dplyr)
library(tidyr)
```


```{r}
company_fundamentals <-
  tribble(
    ~company,     ~revenue_bn, ~net_income_bn, ~employees,
    "Apple",      46.7,        9.4,            34300,
    "Google",     23.7,        6.5,            19835,
    "Microsoft",  58.7,        16.3,           93000,
    "Intel",      35.1,        4.4,            79800,
    "HP",         117.0,       8.0,            304000,
    "IBM",        95.8,        13.4,           399409,
    "Oracle",     23.2,        5.8,            86000,
    "Cisco",      35.5,        6.1,            68574)
  
company_fundamentals
```

```{r}
activity_by_market <-
  tribble(
    ~company, ~procs, ~comps, ~neteqm, ~mobdev, ~sw,
    ~apps, ~webservs, ~ol_ads, ~cloud, ~itservs,
    "Apple",     3L,  1L,  NA,  1L,  1L,  1L,  2L,  3L,  NA,  NA,
    "Google",    NA,  3L,  NA,  3L,  1L,  NA,  1L,  1L,  1L,  NA,
    "Microsoft", NA,  NA,  NA,  3L,  1L,  1L,  1L,  1L,  1L,  2L,
    "Intel",     1L,  NA,  NA,  NA,  1L,  NA,  NA,  NA,  NA,  NA,
    "HP",        NA,  1L,  1L,  1L,  1L,  NA,  3L,  NA,  2L,  1L,
    "IBM",       1L,  1L,  2L,  NA,  1L,  3L,  3L,  NA,  1L,  1L,
    "Oracle",    1L,  1L,  3L,  NA,  1L,  1L,  2L,  NA,  NA,  2L,
    "Cisco",     1L,  2L,  1L,  3L,  NA,  NA,  1L,  NA,  NA,  1L,)

activity_by_market
```


```{r}
order_companies <- c("Apple", "Google", "Microsoft", "Intel", "HP", "IBM", "Oracle", "Cisco")
order_fundamentals <- c("revenue_bn", "net_income_bn", "employees")
order_markets <- c("procs", "comps", "neteqm", "mobdev", "sw", "apps", "webservs", "ol_ads", "cloud", "itservs")

row_captions <-
  c(revenue_bn = "Revenue, 2009, $bn", net_income_bn = "Net income, 2009, $bn",
    employees = "Employees, latest", procs = "Processors", comps = "Computers",
    neteqm = "Network equipment", mobdev = "Mobile devices", sw = "Software",
    apps = "Applications", webservs = "Web-based services",
    ol_ads = "Online advertising", cloud = "Cloud Computing",
    itservs = "IT services/consulting")
```


```{r}
company_fundamentals_w <- 
  company_fundamentals %>%
  tidyr::gather(metric, value, revenue_bn, net_income_bn, employees, -company) %>%
  tidyr::spread(key = company, value) %>%
  dplyr::arrange(factor(metric, levels = order_fundamentals)) %>%
  dplyr::select("metric", order_companies)

company_fundamentals_w
```


```{r}

activity_by_market_w <- 
  activity_by_market %>%
  tidyr::gather(metric, value, 2:ncol(activity_by_market), -company) %>%
  tidyr::spread(key = company, value) %>%
  dplyr::arrange(factor(metric, levels = order_markets)) %>%
  dplyr::select("metric", order_companies) %>%
  dplyr::mutate(groupname = "activity_levels")

activity_by_market_w
```

```{r}
combined_tibble <- 
  bind_rows(company_fundamentals_w, activity_by_market_w) %>%
  rename(rowname = metric) %>%
  mutate(groupname = ifelse(!is.na(groupname), "Amount of activity in each market", groupname))
  
combined_tibble$rowname <- row_captions

combined_tibble
```


```{r}
data <-
  gt(data = combined_tibble) %>%
  cols_align("center") %>%
  tab_stubhead_caption(md("**Company**")) %>%
  fmt_missing(columns = TRUE, missing_text = " ") %>%
  fmt_number(columns = TRUE, rows = c(1, 2), decimals = 1) %>%
  fmt_number(columns = TRUE, rows = 3, decimals = 0) %>%
  tab_heading(title = md("**Tech giants invade each other's turf**")) %>%
  tab_style(
    style = paste0(apply_styles(text_align = "left", text_indent = 5), "padding-bottom:20px"),
    locations = cells_title(groups = "title")
    ) %>%
  tab_style(
    style = apply_styles(text_weight = "bold"),
    locations = cells_boxhead(columns = TRUE)
    ) %>%
  tab_style(
    style = apply_styles(text_stretch = "ultra-condensed"),
    locations = cells_stub(rows = TRUE)
    ) %>%
  tab_options(heading.border.bottom.width = px(0))

data
```


