gt_options_default <- function() {

  dplyr::tribble(
    ~parameter,                           ~scss, ~category,             ~value,
    "table_id",                          FALSE,  "table",               NA_character_,
    "table_font_size",                    TRUE,  "table",               "16px",
    "table_background_color",             TRUE,  "table",               "#FFFFFF",
    "table_width",                        TRUE,  "table",               "auto",
    "table_border_top_style",             TRUE,  "table",               "solid",
    "table_border_top_width",             TRUE,  "table",               "2px",
    "table_border_top_color",             TRUE,  "table",               "#A8A8A8",
    "heading_background_color",           TRUE,  "heading",             NA_character_,
    "heading_title_font_size",            TRUE,  "heading",             "125%",
    "heading_subtitle_font_size",         TRUE,  "heading",             "85%",
    "heading_border_bottom_style",        TRUE,  "heading",             "solid",
    "heading_border_bottom_width",        TRUE,  "heading",             "2px",
    "heading_border_bottom_color",        TRUE,  "heading",             "#A8A8A8",
    "column_labels_background_color",     TRUE,  "columns",             NA_character_,
    "column_labels_font_size",            TRUE,  "columns",             "16px",
    "column_labels_font_weight",          TRUE,  "columns",             "initial",
    "column_labels_hidden",               FALSE,  "columns",            "FALSE",
    "row_group_background_color",         TRUE,  "row_group",           NA_character_,
    "row_group_font_size",                TRUE,  "row_group",           "16px",
    "row_group_font_weight",              TRUE,  "row_group",           "initial",
    "row_group_border_top_style",         TRUE,  "row_group",           "solid",
    "row_group_border_top_width",         TRUE,  "row_group",           "2px",
    "row_group_border_top_color",         TRUE,  "row_group",           "#A8A8A8",
    "row_group_border_bottom_style",      TRUE,  "row_group",           "solid",
    "row_group_border_bottom_width",      TRUE,  "row_group",           "2px",
    "row_group_border_bottom_color",      TRUE,  "row_group",           "#A8A8A8",
    "table_body_border_top_style",        TRUE,  "table_body",          "solid",
    "table_body_border_top_width",        TRUE,  "table_body",          "2px",
    "table_body_border_top_color",        TRUE,  "table_body",          "#A8A8A8",
    "table_body_border_bottom_style",     TRUE,  "table_body",          "solid",
    "table_body_border_bottom_width",     TRUE,  "table_body",          "2px",
    "table_body_border_bottom_color",     TRUE,  "table_body",          "#A8A8A8",
    "row_padding",                        TRUE,  "row",                 "8px",
    "row_striping_include_stub",         FALSE,  "row",                 "FALSE",
    "row_striping_include_table_body",   FALSE,  "row",                 "TRUE",
    "summary_row_background_color",       TRUE,  "summary_row",         NA_character_,
    "summary_row_padding",                TRUE,  "summary_row",         "8px",
    "summary_row_text_transform",         TRUE,  "summary_row",         "inherit",
    "grand_summary_row_background_color", TRUE,  "grand_summary_row",   NA_character_,
    "grand_summary_row_padding",          TRUE,  "grand_summary_row",   "8px",
    "grand_summary_row_text_transform",   TRUE,  "grand_summary_row",   "inherit",
    "footnote_sep",                      FALSE,  "footnote",            "<br />",
    "footnote_glyph",                    FALSE,  "footnote",            "numbers",
    "footnote_font_size",                 TRUE,  "footnote",            "90%",
    "footnote_padding",                   TRUE,  "footnote",            "4px",
    "sourcenote_font_size",               TRUE,  "sourcenote",          "90%",
    "sourcenote_padding",                 TRUE,  "sourcenote",          "4px",
    ) %>%
    as.data.frame()
}
