gt_options_default <- function() {

  dplyr::tribble(
    ~parameter,                           ~scss, ~category,             ~value,
    "table_font_size",                    TRUE,  "table",               "16px",
    "table_background_color",             TRUE,  "table",               "#FFFFFF",
    "table_width",                        TRUE,  "table",               "auto",
    "table_border_top_style",             TRUE,  "table",               "solid",
    "table_border_top_width",             TRUE,  "table",               "2px",
    "table_border_top_color",             TRUE,  "table",               "#A8A8A8",
    "heading_background_color",           TRUE,  "heading",             NA_character_,
    "heading_title_font_size",            TRUE,  "heading",             "125%",
    "heading_subtitle_font_size",         TRUE,  "heading",             "85%",
    "heading_border_bottom_style",        TRUE,  "heading",             "solid",
    "heading_border_bottom_width",        TRUE,  "heading",             "2px",
    "heading_border_bottom_color",        TRUE,  "heading",             "#A8A8A8",
    "columns_background_color",           TRUE,  "columns",             NA_character_,
    "columns_font_size",                  TRUE,  "columns",             "16px",
    "columns_font_weight",                TRUE,  "columns",             "initial",
    "stub_group_background_color",        TRUE,  "stub_group",          NA_character_,
    "stub_group_font_size",               TRUE,  "stub_group",          "16px",
    "stub_group_font_weight",             TRUE,  "stub_group",          "initial",
    "stub_group_border_top_style",        TRUE,  "stub_group",          "solid",
    "stub_group_border_top_width",        TRUE,  "stub_group",          "2px",
    "stub_group_border_top_color",        TRUE,  "stub_group",          "#A8A8A8",
    "stub_group_border_bottom_style",     TRUE,  "stub_group",          "solid",
    "stub_group_border_bottom_width",     TRUE,  "stub_group",          "2px",
    "stub_group_border_bottom_color",     TRUE,  "stub_group",          "#A8A8A8",
    "field_border_top_style",             TRUE,  "field",               "solid",
    "field_border_top_width",             TRUE,  "field",               "2px",
    "field_border_top_color",             TRUE,  "field",               "#A8A8A8",
    "field_border_bottom_style",          TRUE,  "field",               "solid",
    "field_border_bottom_width",          TRUE,  "field",               "2px",
    "field_border_bottom_color",          TRUE,  "field",               "#A8A8A8",
    "row_padding",                        TRUE,  "row",                 "10px",
    "row_striping_include_stub",          TRUE,  "row",                 "TRUE",
    "row_striping_include_field",         TRUE,  "row",                 "TRUE",
    "summary_row_background_color",       TRUE,  "summary_row",         NA_character_,
    "summary_row_padding",                TRUE,  "summary_row",         "6px",
    "summary_row_text_transform",         TRUE,  "summary_row",         "inherit",
    "footnote_sep",                      FALSE,  "footnote",            "<br />",
    "footnote_glyph",                    FALSE,  "footnote",            "numbers",
    "footnote_font_size",                 TRUE,  "footnote",            "90%",
    "footnote_padding",                   TRUE,  "footnote",            "4px",
    "sourcenote_font_size",               TRUE,  "sourcenote",          "90%",
    "sourcenote_padding",                 TRUE,  "sourcenote",          "4px") %>%
    as.data.frame()
}
