#' Save a \pkg{gt} table as a file
#'
#' The `gtsave()` function makes it easy to save a \pkg{gt} table to a file. The
#' function guesses the file type by the extension provided in the output
#' filename, producing either an HTML, PDF, PNG, LaTeX, or RTF file.
#'
#' Output filenames with either the `.html` or `.htm` extensions will produce an
#' HTML document. In this case, we can pass a `TRUE` or `FALSE` value to the
#' `inline_css` option to obtain an HTML document with inlined CSS styles (the
#' default is `FALSE`). More details on CSS inlining are available at
#' [as_raw_html()]. We can pass values to arguments in [htmltools::save_html()]
#' through the `...`. Those arguments are either `background` or `libdir`,
#' please refer to the \pkg{htmltools} documentation for more details on the use
#' of these arguments.
#'
#' We can create an image file based on the HTML version of the `gt` table. With
#' the filename extension `.png`, we get a PNG image file. A PDF document can be
#' generated by using the `.pdf` extension. This process is facilitated by the
#' \pkg{webshot} package, so, this package needs to be installed before
#' attempting to save any table as an image file. There is the option of passing
#' values to the underlying [webshot::webshot()] function though `...`. Some of
#' the more useful arguments for PNG saving are `zoom` (defaults to a scale
#' level of `2`) and `expand` (adds whitespace pixels around the cropped table
#' image, and has a default value of `5`). There are several more options
#' available so have a look at the \pkg{webshot} documentation for further
#' details.
#'
#' If the output filename extension is either of `.tex`, `.ltx`, or `.rnw`, a
#' LaTeX document is produced. An output filename of `.rtf` will generate an RTF
#' document. The LaTeX and RTF saving functions don't have any options to pass
#' to `...`.
#'
#' @param data A table object that is created using the [gt()] function.
#' @param filename The file name to create on disk. Ensure that an extension
#'   compatible with the output types is provided (`.html`, `.tex`, `.ltx`,
#'   `.rtf`). If a custom save function is provided then the file extension is
#'   disregarded.
#' @param path An optional path to which the file should be saved (combined with
#'   filename).
#' @param ... All other options passed to the appropriate internal saving
#'   function.
#'
#' @examples
#' \dontrun{
#' # Use `gtcars` to create a gt table; add
#' # a stubhead label to describe what is
#' # in the stub
#' tab_1 <-
#'   gtcars %>%
#'   dplyr::select(model, year, hp, trq) %>%
#'   dplyr::slice(1:5) %>%
#'   gt(rowname_col = "model") %>%
#'   tab_stubhead_label(label = "car")
#'
#' # Get an HTML file with inlined CSS
#' # (which is necessary for including the
#' # table as part of an HTML email)
#' tab_1 %>%
#'   gtsave("tab_1.html", inline_css = TRUE)
#'
#' # By leaving out the `inline_css` option,
#' # we get a more conventional HTML file
#' # with embedded CSS styles
#' tab_1 %>% gtsave("tab_1.html")
#'
#' # Save the HTML table as a PDF file; we
#' # can optionally add a separate `path`
#' tab_1 %>%
#'   gtsave("tab_1.pdf", path = "~")
#'
#' # Saving as PNG file results in a cropped
#' # image of an HTML table; the overall size
#' # and amount of whitespace can both be set
#' tab_1 %>%
#'   gtsave(
#'     "tab_1.png",
#'     zoom = 2.5,
#'     expand = 10
#'   )
#'
#' # Any use of the `.tex`, `.ltx`, or `.rnw`
#' # will result in the output of a LaTeX
#' # document
#' tab_1 %>% gtsave("tab_1.tex")
#'
#' # An RTF file will be written when using
#' # the `.rtf` extension
#' tab_1 %>% gtsave("tab_1.rtf")
#' }
#' @export
gtsave <- function(data,
                   filename,
                   path = NULL,
                   ...) {

  # Input object validation
  stop_if_not_gt(data)

  # Get the lowercased file extension
  file_ext <- gtsave_file_ext(filename)

  ext_supported_text <-
    paste0(
      "We can use:\n",
      " * `.html`, `.htm` (HTML file)\n",
      " * `.png`          (PNG file)\n",
      " * `.pdf`          (PDF file)\n",
      " * `.tex`, `.rnw`  (LaTeX file)\n",
      " * `.rtf`          (RTF file)\n"
    )

  # Stop function if a file extension is not provided
  if (file_ext == "") {

    stop("A file extension is required in the provided filename. ",
         ext_supported_text,
         call. = FALSE)
  }

  # Use the appropriate save function based
  # on the filename extension
  switch(file_ext,
          "htm" = ,
         "html" = gt_save_html(data, filename, path, ...),
          "ltx" = , # We don't verbally support using `ltx`
          "rnw" = ,
          "tex" = gt_save_latex(data, filename, path, ...),
          "rtf" = gt_save_rtf(data, filename, path, ...),
          "png" = ,
          "pdf" = gt_save_webshot(data, filename, path, ...),
         {
           stop("The file extension used (`.", file_ext, "`) doesn't have an ",
                "associated saving function. ",
                ext_supported_text,
                call. = FALSE)
         }
  )
}

#' Saving function for an HTML file
#'
#' @noRd
gt_save_html <- function(data,
                         filename,
                         path = NULL,
                         ...,
                         inline_css = FALSE) {

  # Combine `path` with `filename` if necessary
  # and normalize the path
  if (!is.null(path)) {
    filename <- file.path(path, filename)
  }
  filename <- filename %>% path_expand()

  if (inline_css) {

    data %>%
      as_raw_html(inline_css = inline_css) %>%
      htmltools::HTML() %>%
      htmltools::save_html(filename, ...)

  } else {

    data %>%
      htmltools::as.tags() %>%
      htmltools::save_html(filename, ...)
  }
}

#' Saving function for an image file via the webshot package
#'
#' @noRd
gt_save_webshot <- function(data,
                            filename,
                            path = NULL,
                            ...,
                            zoom = 2,
                            expand = 5) {

  # Combine `path` with `filename` if necessary
  # and normalize the path
  if (!is.null(path)) {
    filename <- file.path(path, filename)
  }
  filename <- filename %>% path_expand()

  # Create a temporary file with the `html` extension
  tempfile_ <- tempfile(fileext = ".html")

  # Reverse slashes on Windows filesystems
  tempfile_ <-
    tempfile_ %>%
    tidy_gsub("\\\\", "/")

  # Save gt table as HTML using the `gt_save_html()` function
  data %>% gt_save_html(filename = tempfile_, path = NULL)

  # Saving an image requires the webshot package; if it's
  # not present, stop with a message
  if (!requireNamespace("webshot", quietly = TRUE)) {

    stop("The `webshot` package is required for saving images of gt tables.",
         call. = FALSE)

  } else {

    # Save the image in the working directory
    webshot::webshot(
      url = paste0("file:///", tempfile_),
      file = filename,
      selector = "table",
      zoom = zoom,
      expand = expand,
      ...
    )
  }
}

#' Saving function for a LaTeX file
#'
#' @noRd
gt_save_latex <- function(data,
                          filename,
                          path = NULL,
                          ...) {

  # Combine `path` with `filename` if necessary
  # and normalize the path
  if (!is.null(path)) {
    filename <- file.path(path, filename)
  }
  filename <- filename %>% path_expand()

  data %>%
    as_latex() %>%
    writeLines(con = filename)
}

#' Saving function for an RTF file
#'
#' @noRd
gt_save_rtf <- function(data,
                        filename,
                        path = NULL,
                        ...) {

  # Combine `path` with `filename` if necessary
  # and normalize the path
  if (!is.null(path)) {
    filename <- file.path(path, filename)
  }
  filename <- filename %>% path_expand()

  data %>%
    as_rtf() %>%
    writeLines(con = filename)
}

#' Get the lowercase extension from a filename
#'
#' @noRd
gtsave_file_ext <- function(filename) {

  tools::file_ext(filename) %>% tolower()
}
