#' Save a \pkg{gt} table as a file
#'
#' The `gtsave()` function makes it easy to save a \pkg{gt} table to a file. The
#' function guesses the file type by the extension provided in the output
#' filename, producing either an HTML, LaTeX, RTF, PNG, or PDF file.
#'
#' Output filenames with either the `.html` or `.htm` extensions will produce an
#' HTML document. In this case, we can pass a `TRUE` or `FALSE` value to the
#' `inline_css` option to obtain an HTML document with inlined CSS styles (the
#' default is `FALSE`). More details on CSS inlining are available at
#' [as_raw_html()].
#'
#' If the output filename extension is either of `.tex`, `.ltx`, or `.rnw`, a
#' LaTeX document is produced. An output filename of `.rtf` will generate an RTF
#' document. The LaTeX and RTF saving functions don't have any options to pass
#' to `...`.
#'
#' We can create an image file based on the HTML version of the `gt` table. With
#' the filename extension `.png`, we get a PNG image file. A PDF document can be
#' generated by using the `.pdf` extension.
#'
#' @param data A table object that is created using the [gt()] function.
#' @param filename The file name to create on disk. Ensure that an extension
#'   compatible with the output types is provided (`.html`, `.tex`, `.ltx`,
#'   `.rtf`). If a custom save function is provided then the file extension is
#'   disregarded.
#' @param path An optional path to which the file should be saved (combined with
#'   filename).
#' @param ... All other options passed to the appropriate internal saving
#'   function.
#' @export
gtsave <- function(data,
                   filename,
                   path = NULL,
                   ...) {

  # Input object validation
  stop_if_not_gt(data)

  # Get the lowercased file extension
  file_ext <- gtsave_file_ext(filename)

  # Stop function if a file extension is not provided
  if (file_ext == "") {

    stop("A file extension is required in the provided filename. We can use:\n",
         " * `.html`/`.htm` (HTML file)\n",
         " * `.tex`/`.ltx`/`.rnw` (LaTeX file)\n",
         " * `.rtf` (RTF file)\n",
         " * `.png` (PNG file)\n",
         " * `.pdf` (PDF file)",
         call. = FALSE)
  }

  # Use the appropriate save function based
  # on the filename extension
  switch(file_ext,
          htm = ,
         html = gt_save_html(data, filename, path, ...),
          ltx = ,
          rnw = ,
          tex = gt_save_latex(data, filename, path, ...),
          rtf = gt_save_rtf(data, filename, path, ...),
          png = ,
          pdf = gt_save_webshot(data, filename, path, ...),
         {
           stop("The file extension used (`.", file_ext, "`) doesn't have an ",
                "associated saving function.\n",
                " * We can use either of `.html`/`.htm`, ",
                "`.tex`/`.ltx`/`.rnw`, `.png`, or `.rtf`",
                call. = FALSE)
         }
  )
}

#' Saving function for an HTML file
#'
#' @importFrom htmltools as.tags save_html HTML
#' @noRd
gt_save_html <- function(data,
                         filename,
                         path = NULL,
                         ...,
                         inline_css = FALSE) {

  # Combine `path` with `filename` if necessary
  # and normalize the path
  if (!is.null(path)) {
    filename <- file.path(path, filename)
  }
  filename <- filename %>% path_expand()

  if (inline_css) {

    data %>%
      as_raw_html(inline_css = inline_css) %>%
      htmltools::HTML() %>%
      htmltools::save_html(filename, ...)

  } else {

    data %>%
      htmltools::as.tags() %>%
      htmltools::save_html(filename, ...)
  }
}

#' Saving function for an image file via the webshot package
#'
#' @noRd
gt_save_webshot <- function(data,
                            filename,
                            path = NULL,
                            ...,
                            zoom = 2,
                            expand = 5) {

  # Combine `path` with `filename` if necessary
  # and normalize the path
  if (!is.null(path)) {
    filename <- file.path(path, filename)
  }
  filename <- filename %>% path_expand()

  # Create a temporary file with the `html` extension
  tempfile_ <- tempfile(fileext = ".html")

  # Reverse slashes on Windows filesystems
  tempfile_ <-
    tempfile_ %>%
    tidy_gsub("\\\\", "/")

  # Save gt table as HTML using the `gt_save_html()` function
  data %>% gt_save_html(filename = tempfile_, path = NULL)

  # Saving an image requires the webshot package; if it's
  # not present, stop with a message
  if (!requireNamespace("webshot", quietly = TRUE)) {

    stop("The `webshot` package is required for saving images of gt tables.",
         call. = FALSE)

  } else {

    # Save the image in the working directory
    webshot::webshot(
      url = paste0("file:///", tempfile_),
      file = filename,
      selector = "table",
      zoom = zoom,
      expand = expand,
      ...
    )
  }
}

#' Saving function for a LaTeX file
#'
#' @noRd
gt_save_latex <- function(data,
                          filename,
                          path = NULL,
                          ...) {

  # Combine `path` with `filename` if necessary
  # and normalize the path
  if (!is.null(path)) {
    filename <- file.path(path, filename)
  }
  filename <- filename %>% path_expand()

  data %>%
    as_latex() %>%
    writeLines(con = filename)
}

#' Saving function for an RTF file
#'
#' @noRd
gt_save_rtf <- function(data,
                        filename,
                        path = NULL,
                        ...) {

  # Combine `path` with `filename` if necessary
  # and normalize the path
  if (!is.null(path)) {
    filename <- file.path(path, filename)
  }
  filename <- filename %>% path_expand()

  data %>%
    as_rtf() %>%
    writeLines(con = filename)
}

#' Get the lowercase extension from a filename
#'
#' @importFrom tools file_ext
#' @noRd
gtsave_file_ext <- function(filename) {

  tools::file_ext(filename) %>% tolower()
}
